### ISSUE TITLE
Engine build fails

### ISSUE THREAD

**Issue by pwasowski2** [flutter-tizen/engine#68]
I am trying to build engine from flutter-tizen/engine repo, to use it with flutter. I am following the manual from https://github.com/flutter-tizen/engine/wiki/Building-the-engine and I have been stuck on point 5. from this part of the manual https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment:

> 5. gclient sync in that [flutter/engine] directory. This will fetch all the source code that Flutter depends on. Avoid interrupting this script, as doing so can leave your repository in an inconsistent state that is tedious to clean up. (This step automatically runs git clone, among other things.)

When I use "https://github.com/flutter-tizen/engine.git" as the "url" in .gclient file, the `gclient sync` command fails with the following output:

```
(flutter) [~/prog/github/flutter/engine]$ gclient sync                                                                                            *[master]

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://github.com/flutter-tizen/engine.git /home/p.wasowski2/prog/github
/flutter/engine/src/_gclient_flutter_rgad74su' in '/home/p.wasowski2/prog/github/flutter/engine'
Cloning into '/home/p.wasowski2/prog/github/flutter/engine/src/_gclient_flutter_rgad74su'...
remote: Enumerating objects: 220707, done.
remote: Total 220707 (delta 0), reused 0 (delta 0), pack-reused 220707
Receiving objects: 100% (220707/220707), 208.27 MiB | 28.70 MiB/s, done.
Resolving deltas: 100% (161411/161411), done.
Checking connectivity... done.
Syncing projects: 100% (106/106), done.

Running hooks:  77% ( 7/ 9) linux_sysroot_x64
________ running 'vpython src/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/home/p.wasowski2/prog/github/flutter/engine'
Installing Debian sid amd64 root image: /home/p.wasowski2/prog/github/flutter/engine/src/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/79a7783607a69b6f439add567eb6fcb48877085c/debian_sid_amd64_sysroot.tar.xz
Running hooks:  88% ( 8/ 9) linux_sysroot_arm64
________ running 'vpython src/build/linux/sysroot_scripts/install-sysroot.py --arch=arm64' in '/home/p.wasowski2/prog/github/flutter/engine'
Installing Debian sid arm64 root image: /home/p.wasowski2/prog/github/flutter/engine/src/build/linux/debian_sid_arm64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/2cade9ee1ca9186b28ac768c19e1ab7c45ee0600/debian_sid_arm64_sysroot.tar.xz
Running hooks: 100% ( 9/ 9) dart package config
________ running 'vpython src/flutter/tools/run_third_party_dart.py' in '/home/p.wasowski2/prog/github/flutter/engine'
Resolving dependencies...
+ charcode 1.2.0
+ collection 1.15.0
+ package_config 2.0.0
+ path 1.8.0
+ pub_semver 2.0.0
+ source_span 1.8.1
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ yaml 3.1.0
Changed 9 dependencies!
Package generate_package_config is currently active at path "/home/p.wasowski2/prog/github/flutter/engine/src/flutter/tools/generate_package_config".
Activated generate_package_config 0.0.0 at path "/home/p.wasowski2/prog/github/flutter/engine/src/flutter/tools/generate_package_config".
Unable to spawn isolate: src/flutter/tools/generate_package_config/bin/generate_from_legacy.dart:10:8: Error: Error when reading '../../../../.pub-cache/host
ed/pub.dartlang.org/package_config-2.0.0/lib/packages_file.dart': No such file or directory
import 'package:package_config/packages_file.dart'; // ignore: deprecated_member_use
       ^
src/flutter/tools/generate_package_config/bin/generate_from_legacy.dart:28:20: Error: Method not found: 'parse'.
  var packageMap = parse(await packagesFile.readAsBytes(), packagesFile.uri);
                   ^^^^^
Traceback (most recent call last):
  File "src/flutter/tools/run_third_party_dart.py", line 14, in <module>
    subprocess.check_call([os.path.join(leading, pub), "global", "run", "generate_package_config:generate_from_legacy", "src/flutter/flutter_frontend_server/
.packages"])
  File "/home/p.wasowski2/prog/github/depot_tools/bootstrap-3.8.0.chromium.8_bin/python/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['src/third_party/dart/tools/sdks/dart-sdk/bin/pub', 'global', 'run', 'generate_package_config:generate_from_legacy',
 'src/flutter/flutter_frontend_server/.packages']' returned non-zero exit status 1
Error: Command 'vpython src/flutter/tools/run_third_party_dart.py' returned non-zero exit status 1 in /home/p.wasowski2/prog/github/flutter/engine
```

The contents of .gclient file in flutter/engine:
```
solutions = [
  {
    "managed": False,
    "name": "src/flutter",
    "url": "https://github.com/flutter-tizen/engine.git",
    "custom_deps": {},
    "deps_file": "DEPS",
    "safesync_url": "",
  },
]
```

As a workaround I have changed the version of `package_config` in `flutter/engine/src/flutter/tools/generate_package_config/pubspec.yaml` from `any` to `1.9.3` - after that change `gclient sync` succeeds. Nevertheless, this is only a workaround.

**Could you please help me fixing the problem?**

**Comment by swift-kim** [comment]
I tried to reproduce but my gclient hangs forever at:

```sh
$ gclient sync
Syncing projects:  38% (41/106) src/third_party/libwebp
```

**Comment by swift-kim** [comment]
My problem was resolved by setting `"https://github.com/flutter/engine.git"` (the upstream repo) as the value of `"url"`.

```sh
# Run sync once.
$ gclient sync

# Fetch flutter-tizen/engine.
$ cd src/flutter
$ git remote add tizen https://github.com/flutter-tizen/engine.git
$ git fetch tizen
$ git checkout flutter-2.0.1-tizen
$ cd -

# Run sync again (because we changed HEAD).
$ gclient sync -D
```

This is also a kind of workaround but may solve your problem as well.

**Comment by pwasowski2** [comment]
Thanks for that, it looks simpler than the one I've found before :)
